version: '3'

services:
  mongodb:
    image: mongo
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DATABASE_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - mongodb_data:/data/db

  redis:
    image: redis
    ports:
      - 6379:6379

  backend:
    image: minhpq331/video-sharing-example-backend:${IMAGE_TAG}
    ports:
      - 3000:3000
    environment:
      - PORT=3000
      - DATABASE_URI=mongodb://${DATABASE_USERNAME}:${DATABASE_PASSWORD}@mongodb:27017/video-sharing-example
      - REDIS_URI=redis://redis:6379
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - mongodb
      - redis

  frontend:
    image: minhpq331/video-sharing-example-frontend:${IMAGE_TAG}
    ports: 
      - 8080:8080
    environment:
      - API_BASE_URL=https://backend.toanhoczero.com
      - WEBSOCKET_URL=https://backend.toanhoczero.com
    depends_on:
      - backend

  nginx:
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend
      - backend

volumes:
  mongodb_data: