version: '3'

services:
  mongodb:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db

  redis:
    image: redis
    ports:
      - 6379:6379

  backend:
    build: ./backend
    ports:
      - 3000:3000
    environment:
      - PORT=3000
      - DATABASE_URI=mongodb://mongodb:27017/video-sharing-example
      - REDIS_URI=redis://redis:6379
      - JWT_SECRET=supersecret
    depends_on:
      - mongodb
      - redis

  frontend:
    build: ./frontend
    ports: 
      - 8080:8080
    environment:
      - API_URL=http://127.0.0.1:3000
    depends_on:
      - backend

volumes:
  mongodb_data: